# Generated by Django 5.2.1 on 2025-05-16 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_ticket_alter_message_id'),
        ('ticket', '0003_remove_ticket_messages_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket'),
        ),
    ]
