# Generated by Django 5.2.1 on 2025-05-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_ticket_alter_message_id'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='message.message'),
        ),
    ]
