# Generated by Django 5.2.1 on 2025-05-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='messages',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
